version: '2'
services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
  mq:
    build: ./mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQSNOAUT: "no"
    ports:
      - "1414:1414"
      - "9443:9443"
  pse-service:
    build: ./participant-security-enquiry
    ports:
      - "8080:8080"
    volumes: 
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - mq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/pse_service
      SPRING_DATASOURCE_USERNAME: postgresuser
      SPRING_DATASOURCE_PASSWORD: postgrespw
      JAVA_OPTS: -Xmx192m
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
    command: mvn clean package spring-boot:run
  css-service:
    build: ./central-security-settlement
    ports:
      - "8081:8080"
    volumes: 
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - mq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/css_service
      SPRING_DATASOURCE_USERNAME: postgresuser
      SPRING_DATASOURCE_PASSWORD: postgrespw
      JAVA_OPTS: -Xmx192m
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      DOCKER_HOST_IP : ${DOCKER_HOST_IP}
    command: mvn clean package spring-boot:run
